# Generated by Django 4.2.1 on 2023-05-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='status',
            field=models.CharField(blank=True, choices=[('PUNAINEN', 'Punainen'), ('MUSTA', 'Musta'), ('SININEN', 'Sininen'), ('VALKOINEN', 'Valkoinen'), ('KELTAINEN', 'Keltainen'), ('VIHREÄ', 'Vihreä')], max_length=20),
        ),
    ]
