# Generated by Django 4.2.1 on 2023-05-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportdiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
